# **Naive Bayes Algorithm**
---
### Author :  Muhammad Ali Saagar

**Python Developer • Data Science • AI/ML Engineer**

#### 🔗 Connect With Me

[![GitHub](https://img.shields.io/badge/GitHub-Profile-181717?style=for-the-badge\&logo=github)](https://github.com/AliMuhammad78)
[![LinkedIn](https://img.shields.io/badge/LinkedIn-Profile-0A66C2?style=for-the-badge\&logo=linkedin)](https://www.linkedin.com/in/muhammad-ali-91294a290)
[![Kaggle](https://img.shields.io/badge/Kaggle-Profile-20BEFF?style=for-the-badge\&logo=kaggle)](https://www.kaggle.com/ali98muhammad45)
[![YouTube](https://img.shields.io/badge/YouTube-Channel-FF0000?style=for-the-badge\&logo=youtube)](https://www.youtube.com/@TechyBits20121)
[![Email](https://img.shields.io/badge/Email-Contact-D14836?style=for-the-badge\&logo=gmail)](mailto:alisaagar86@gmail.com)

### Acknowledgement

> Most of the examples in this notebook are based on the excellent tutorials by **Dr. Muhammad Aammar Tufail (Codanics)**. I sincerely thank him for sharing his knowledge and practical examples.

 [![GitHub](https://img.shields.io/badge/GitHub-Profile-181717?style=for-the-badge\&logo=github)](https://github.com/AammarTufail)
[![LinkedIn](https://img.shields.io/badge/LinkedIn-Profile-0A66C2?style=for-the-badge\&logo=linkedin)](https://www.linkedin.com/in/dr-muhammad-aammar-tufail-02471213b/)
[![Kaggle](https://img.shields.io/badge/Kaggle-Profile-20BEFF?style=for-the-badge\&logo=kaggle)](https://www.kaggle.com/muhammadaammartufail)
[![YouTube](https://img.shields.io/badge/YouTube-Channel-FF0000?style=for-the-badge\&logo=youtube)](https://www.youtube.com/@codanics)

---
# **Naive Bayes Algorithm**
Naive Bayes is a **supervised machine learning algorithm** mainly used for **classification tasks**.  
It is based on **Bayes' Theorem**, with a strong assumption that features are **independent** of each other.

---

## **Bayes' Theorem**
 $$ 
P(A|B) = \frac{P(B|A) \cdot P(A)}{P(B)}

 $$
Where:
- **P(A|B)** → Posterior probability (probability of class given features)  
- **P(B|A)** → Likelihood (probability of features given class)  
- **P(A)** → Prior probability (probability of class)  
- **P(B)** → Evidence (probability of features)  

---

## **Why is it called "Naive"?**
- It assumes that **all features are independent** of each other.
- In real-world data, this assumption is often false, but the algorithm still performs surprisingly well.

---

## **Types of Naive Bayes**
1. **Gaussian Naive Bayes**
   - Used for **continuous data**
   - Assumes data follows a normal distribution  

2. **Multinomial Naive Bayes**
   - Used for **discrete data** (e.g., word counts in text classification)  

3. **Bernoulli Naive Bayes**
   - Used for **binary features** (0 or 1)  

---

## **How it Works**
1. Calculate prior probabilities for each class  
2. Compute likelihood of features given each class  
3. Apply Bayes' theorem to compute posterior probabilities  
4. Choose the class with the **highest probability**  

---

## **Advantages**
- Simple and easy to implement  
- Works well with **high-dimensional data**  
- Fast training and prediction  
- Performs well in **text classification** (e.g., spam detection)  

---

## **Limitations**
- Assumes feature independence (not always realistic)  
- Performance may drop if features are highly correlated  
- Requires proper probability handling (zero-frequency problem)  

---

## **Common Use Cases**
- Spam email detection  
- Sentiment analysis  
- Document classification  
- Medical diagnosis  

---

## **Key Insight**
Even though the independence assumption is unrealistic, **Naive Bayes often performs very well in practice**, especially for text and categorical data.

---

# Code Implementation 

In [ ]:
import pandas as pd 
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt 

from sklearn.naive_bayes import GaussianNB , MultinomialNB , BernoulliNB
from sklearn.model_selection import train_test_split 
from sklearn.metrics import accuracy_score , confusion_matrix , classification_report 

In [2]:
# load the dataset
df = sns.load_dataset('iris')
print(df.head())
X = df.drop('species', axis=1)
y = df['species']

# train test split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa


In [3]:
# model initialize
gnb = GaussianNB()

# train the model
gnb.fit(X_train, y_train)

# predict the test data
y_pred = gnb.predict(X_test)

# evaluate the model
print("Accuracy Score: ", accuracy_score(y_test, y_pred))
print("Confusion Matrix: \n", confusion_matrix(y_test, y_pred))
print("Classification Report: \n", classification_report(y_test, y_pred))

Accuracy Score:  1.0
Confusion Matrix: 
 [[15  0  0]
 [ 0 11  0]
 [ 0  0 12]]
Classification Report: 
               precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        15
  versicolor       1.00      1.00      1.00        11
   virginica       1.00      1.00      1.00        12

    accuracy                           1.00        38
   macro avg       1.00      1.00      1.00        38
weighted avg       1.00      1.00      1.00        38



In [4]:
# model initialize
mnb = MultinomialNB()

# train the model
mnb.fit(X_train, y_train)

# predict the test data
y_pred = mnb.predict(X_test)

# evaluate the model
print("Accuracy Score: ", accuracy_score(y_test, y_pred))
print("Confusion Matrix: \n", confusion_matrix(y_test, y_pred))
print("Classification Report: \n", classification_report(y_test, y_pred))

Accuracy Score:  0.9736842105263158
Confusion Matrix: 
 [[15  0  0]
 [ 0 11  0]
 [ 0  1 11]]
Classification Report: 
               precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        15
  versicolor       0.92      1.00      0.96        11
   virginica       1.00      0.92      0.96        12

    accuracy                           0.97        38
   macro avg       0.97      0.97      0.97        38
weighted avg       0.98      0.97      0.97        38



In [5]:
# model initialize
bnb = BernoulliNB()

# train the model
bnb.fit(X_train, y_train)

# predict the test data
y_pred = bnb.predict(X_test)

# evaluate the model
print("Accuracy Score: ", accuracy_score(y_test, y_pred))
print("Confusion Matrix: \n", confusion_matrix(y_test, y_pred))
print("Classification Report: \n", classification_report(y_test, y_pred))

Accuracy Score:  0.2894736842105263
Confusion Matrix: 
 [[ 0 15  0]
 [ 0 11  0]
 [ 0 12  0]]
Classification Report: 
               precision    recall  f1-score   support

      setosa       0.00      0.00      0.00        15
  versicolor       0.29      1.00      0.45        11
   virginica       0.00      0.00      0.00        12

    accuracy                           0.29        38
   macro avg       0.10      0.33      0.15        38
weighted avg       0.08      0.29      0.13        38



c:\Users\zen lab\.conda\envs\python_ml\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\zen lab\.conda\envs\python_ml\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\zen lab\.conda\envs\python_ml\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", res

>   Remember that the implementation of these algorithms is dependent from data to data .  
> 
> Use other data for bernoulli to see the better evaluation 

In [ ]:
> 